# Generated by Django 4.1.5 on 2023-01-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, verbose_name='Имя модели'
                    ),
                ),
                (
                    'load_capacity',
                    models.IntegerField(
                        verbose_name='Максимальная грузоподъёмность'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Модель самосвала',
                'verbose_name_plural': 'Модели самосвалов',
            },
        ),
        migrations.CreateModel(
            name='Dumper',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('tail_number', models.CharField(max_length=255)),
                ('load_weight', models.SmallIntegerField()),
                (
                    'model',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='dumpers.model',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Самосвал',
                'verbose_name_plural': 'Самосвалы',
            },
        ),
    ]
