version: "3.11"
services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --run-syncdb --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - sqlite3
    env_file:
      - .env.example

volumes:
  config_pgdata: